### ISSUE TITLE
Aeson build fails on AWS t2.micro instance with Stack

### ISSUE THREAD

**Issue by patbecich** [bos/aeson#543] opened 2017-04-20 05:04 UTC
I am trying to build this Stack project on an AWS t2.micro Ubuntu instance: https://github.com/patbecich/javascriptSandbox/tree/deploy/phaserTest

The build fails on compiling Aeson:

        [ 9 of 20] Compiling Data.Aeson.Types.FromJSON ( Data/Aeson/Types/FromJSON.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.2.0/build/Data/Aeson/Types/FromJSON.o )

    /tmp/stack7506/aeson-1.0.2.1/Data/Aeson/Types/FromJSON.hs:446:3: warning: [-Winline-rule-shadowing]
        Rule "FromJSONKeyCoerce: fmap id" may never fire
          because ‘id’ might inline first
        Probable fix: add an INLINE[n] or NOINLINE[n] pragma for ‘id’

I tried again with a higher Aeson version by putting this in `stack.yaml`:

     extra-deps: [aeson-1.2.0.0]

Same problem:

    [12 of 23] Compiling Data.Aeson.Types.FromJSON ( Data/Aeson/Types/FromJSON.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.2.0/build/Data/Aeson/Types/FromJSON.o )

    /tmp/stack19515/aeson-1.2.0.0/Data/Aeson/Types/FromJSON.hs:470:3: warning: [-Winline-rule-shadowing]
        Rule "FromJSONKeyCoerce: fmap id" may never fire
          because ‘id’ might inline first
        Probable fix: add an INLINE[n] or NOINLINE[n] pragma for ‘id’

Oddly, the project builds fine with both version of Aeson on my Mac.

Any ideas?  Thanks!

**Comment by phadej** [comment] 2017-04-20 09:32
That's just a warning. I suspect that either stack or ghc is silently killed by OOM. `t2.micro` is a toy instance, you could try limit ghc memory usage, but I don't remember rts options by heart

**Comment by bergmark** [comment] 2017-04-28 11:58
Hi @patbecich, I'd answer the same as phadej. Did you make any progress?

It is possible that aeson consumes more memory than it needs to, and it may warrant a fix if we can figure out the cause. If it turns out it's mostly because of GHC itself then it can be reported upstream. Disregarding aeson I think you will still inevitably run into issues with GHC on only 1GB RAM.

So I think we need more information in order to decide how to proceed.

**Comment by mklinik** [comment] 2017-09-11 09:09
I just had the same problem compiling my project, which depends on aeson, on a virtual server with 1GB memory. Temporarily enabling swap worked for me.

https://medium.com/@saurabhnanda/building-haskell-specifically-lens-library-in-a-low-memory-environment-5ef58ec294a2

**Comment by JasonMFry** [comment] 2018-11-16 16:47
Had the same issue after doing a factory reset on Docker, didn't realize that Docker defaults with 2GB of Memory! Bumped it up to 4GB and it worked.

**Comment by telser** [comment] 2018-11-30 01:52
@JasonMFry That default is really too low :(

This issue should probably be closed by someone who has the ability to do so.

**Closed** 2019-04-08 05:46 UTC
Labels: info needed
