### ISSUE TITLE
Derived `decode` and `encode` don't round trip

### ISSUE THREAD

**Issue by pseudonom** [bos/aeson#334] opened 2016-01-15 17:28 UTC
```haskell
data Foo = Foo | Bar deriving (Show)
deriveJSON defaultOptions ''Foo

encode Foo == "\"Foo\""
decode (encode Foo) == Nothing
```

This behavior seems pretty strange to me.

**Comment by bos** [comment] 2016-01-15 19:38
Duplicate of #327.

**Closed by bos** 2016-01-15 19:38 UTC

**Comment by pseudonom** [comment] 2016-01-15 21:23
Thanks.
