### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by tjilerom** [bos/aeson#740] opened 2019-11-22 22:15 UTC
tests/ErrorMessages.hs:16:29: error: **Module ‘Data.Algorithm.Diff’ does not export ‘PolyDiff(..)’**

`16 | import Data.Algorithm.Diff (PolyDiff (..), getGroupedDiff)
`

**Comment by phadej** [comment] 2019-11-24 15:09
... caused by `Diff-0.4.0` release.

**Comment by bergmark** [comment] 2019-11-24 18:04
Which version of aeson are you using?

I think this was fixed in https://github.com/bos/aeson/pull/732 which was released in 1.4.6.0

**Comment by bergmark** [comment] 2019-11-30 08:21
I believe this is resolved. Let me know if you can give a reproduction and we'll re-open.

**Closed by bergmark** 2019-11-30 08:21 UTC
