### ISSUE TITLE
Ord instance for Value?

### ISSUE THREAD

**Issue by Gabriel439** [bos/aeson#704] opened 2019-05-28 18:16 UTC
I could add an `Ord` instance for `Value` if it would be welcome.  The context for this to be able to store `Value`s inside of a `Set`

**Comment by phadej** [comment] 2019-05-28 18:30
HashMap has `Ord` only since `unordered-containers-2.9.0.0` (http://hackage.haskell.org/package/unordered-containers-0.2.9.0/changelog). which OTOH supports only GHC-7.8 (https://matrix.hackage.haskell.org/#/package/unordered-containers), which would mean narrowing support window.

**Comment by Gabriel439** [comment] 2019-05-28 18:32
Oh, I didn't realize.  Would it be possible to guard the derived `Ord` instance with `#ifdef MIN_VERSION_unordered-containers(2,9,0)`?

**Comment by phadej** [comment] 2019-05-28 18:37
Do you mean having derived `Ord` with newer `unordered-containers`, and hand-written one for older?

**Comment by Gabriel439** [comment] 2019-05-29 02:09
@phadej: I meant enabling the `Ord` instance when building against a sufficiently new version of `unordered-containers`, but now that I write that "out loud" I realize that's probably not a good idea :slightly_smiling_face:

**Comment by bergmark** [comment] 2019-06-13 12:56
We can consider dropping support for older unordered-containers. Looks like we'd lose support for GHC 7.4 & 7.6 while doing that. I think we've mainly kept support for older GHCs because it hasn't cost us anything. More things like this are bound to pop up in the future.

**Comment by fredefox** [comment] 2019-10-17 22:15
This could be a potential instance for `Ord` in the case when the instance of from `unordered-containers` is not available. I haven't checked that they agree. But I would expect that they do.

```
import GHC.Exts (toList)

instance Ord Value where
  compare v0 v1 = case (v0, v1) of
    (Object o0, Object o1) -> mconcat $ zipWith go (toList o0) (toList o1)
      where
      go (t0, v0') (t1, v1') = compare t0 t1 <> compareValue v0' v1'
    (Array a0, Array a1)      -> mconcat $ zipWith compare (toList a0) (toList a1)
    (String s0, String s1)    -> compare s0 s1
    (Number n0, Number n1)    -> compare n0 n1
    (Bool b0, Bool b1)        -> compare b0 b1
    (Null, Null)              -> EQ
    _                         -> (compare `on` cons) v0 v1
      where
      cons :: Value -> Word8
      cons = \case
        Object{} -> 0
        Array{}  -> 1
        String{} -> 2
        Number{} -> 3
        Bool{}   -> 4
        Null{}   -> 5
```

**Comment by phadej** [comment] 2019-10-17 23:03
@fredefox that doesn't work. order of elements in `HashMap` (exposed via `toList`) is non-deterministic (when there are conflicts in internal structure.

Best you can do, is to convert to `containers`' `Map` and compare those.

Also, FYI `zipWith compare` doesn't work in general either (though that relation might be some kind of order), in this case, it's bad idea to compare `Vector`s like that.

```haskell
Prelude> mconcat $ zipWith compare [] [1,2]
EQ
```

Luckily `Vector` does have an `Ord` instance.

**Comment by fredefox** [comment] 2019-10-18 12:02
Ah yes, I didn't consider maps of unequal lengths. Thanks for pointing that out. I suppose this could be fixed by first comparing their lengths.

I'm curious how the non-deterministic order of elements in a `HashMap` manifests itself. Do you mean non-specificed or do you mean that `toList x` may evaluate to different values? I'm curious how these "conflicts" may come about, if you would like to expand on that a bit.

**Comment by phadej** [comment] 2019-10-18 14:20
@fredefox, it's relatively simple to constuct `HashMap`s which are equal, but their `toList` isn't.

Try e.g. with

```haskell
newtype Collision = Collision Int deriving (Eq, Show)
instance Hashble Collision where
    hashWithSalt salt _ = salt -- will collide always

x = HashMap.toList [(Collision 0, 'a'), (Collision 1, 'b')]
y = HashMap.toList [(Collision 1, 'b'), (Collision 0, 'a')]

-- as it's `Eq` which matters, not `Hashable`.
x == y = True
toList x == toList y = {-# might be True or False, you cannot be sure #-}
```

**Comment by TomMD** [comment] 2019-12-05 23:00
I have just been bitten by this too and this thread doesn't seem to have any objections to dropping support for ghc < 7.8.   The newest GHC that will become unsupported is still over 6 years old.   Can we do this please?

**Comment by hvr** [comment] 2019-12-06 07:54
Aeson is a very persasive dependency across Hackage and if aeson drops support for GHC < 7.8 it'll basically mean that it'll kill transitively support for those GHCs; I for one still care to support GHCs back till GHC 7.4 (or even GHC 7.0 when it's cheap) and aeson dropping support would make me consider to fork aeson or switch to a different JSON library. Otoh I do strongly oppose to have a conditional `Ord` instance as a function of the `unordered-containers` version as this would obviously cause a lot of harm as it'd break the versioning contract.

So to me the more reasonable path would be to see if `unordered-containers` can be restored to support older GHCs, at least back to GHC 7.4.2 again.

**Comment by phadej** [comment] 2019-12-06 10:33
I think the ship has sailed with unordered-containers dropping the support for GHCs prior 7.8. If aeson drops support for older GHC, there are still older aeson versions. Situation isn’t IMHO any different, than current when aeson depends on non-recent unordered-containers.

unordered-containers-0.2.9.0 which stopped support was uploaded almost two years ago Mon Feb 5 17:13:02 UTC 2018

There’s plenty of nice clean-up we are able to do, if we support only slightly newer GHC. https://github.com/bos/aeson/commit/4d3767c18ef6c3b4fe5b986fe39b244759f1359e

**Comment by hvr** [comment] 2019-12-06 12:39
There *is* a difference though; I don't need to directly depend on `unordered-containers` (in general I have little need for unordered-containers as its semantics and operational aspects are often not what I need) nor do I need to be aware of HashMap's API in order to use `aeson`; that way I was shielded from `unordered-containers` having regressed in terms of GHC support to the point it didn't affect me. If `aeson` however starts regressing I'd definitely have to actively deal with this, sometimes it might be able to do this by supporting multiple major versions of `aeson` (which comes at a significant cost) but sometimes this isn't possible for various possible reasons.

I still don't understand why `unordered-containers` had to drop support for GHC < 7.8; whether there was actual technical reason that required this. The changelog doesn't give a clear justification for this move. I'm still considering fixing this regression and restoring GHC < 7.8 support to `unordered-containers`.

**Comment by Lysxia** [comment] 2019-12-06 16:19
The original motivation (ping @Gabriel439) is to make sets of `Value`, would `HashSet` do instead of `Set`? There are already `Eq` and `Hashable` instances.

**Comment by phadej** [comment] 2019-12-06 16:19
There's also https://github.com/bos/aeson/issues/741 which would allow simplifying stuff in `aeson`. Some corner cases, but these accumulate. `Coercible` **is** a good reason to drop GHC-7.6 support.

I consider support for GHC-7.8.4 to be quite conservative, it was released 5 years ago.

**Comment by phadej** [comment] 2019-12-06 16:29
@hvr there's also an year old issue in `unordered-container` https://github.com/tibbe/unordered-containers/issues/179, see comment https://github.com/tibbe/unordered-containers/issues/179#issuecomment-360202004

> Do you need them? Why? We actually removed support in the interest of
getting rid of clutter. If we need to revert, you should find that fairly
recent commit helpful. But this all has to happen quick--I want to release
today.

Removing clutter is a good reason. See e.g. https://github.com/tibbe/unordered-containers/commit/f2bf9c5feffeb6abfd4716c8d6f997adc36c5557 commit.

Supporting GHC-7.6 and older is noble, but I there's plenty of CPP around roles (in `unordered-containers`), coercible and template-haskell in `aeson`.

**Comment by Gabriel439** [comment] 2019-12-06 17:01
@Lysxia: I was able to work around the lack of an `Ord` instance on my end (I don't remember exactly how), but the whole reason I opened the issue was so that future users wouldn't have to

@hvr: I agree with the others that we should drop GHC 7.6 support by now.  As @phadej noted, GHC 7.6 users can still use older versions of `aeson`.  If they want a bleeding edge `aeson` then they should pay the freight to upgrade their compiler.  Besides, chances are if they don't have the time or wherewithal to upgrade their compiler after 5 years they probably also are unable to upgrade their `aeson` dependency anyway, so it's a moot point.

Based on a recent survey less than 4% of Haskell users use a GHC version older than GHC 8:

* [2019 State of Haskell Survey results](https://taylor.fausak.me/2019/11/16/haskell-survey-results/#s2q4)

... although it doesn't provide resolution into which pre-8.0 versions they still use.  I imagine the set of people on 7.6 or older are a small subset of that 4%.

Given that so few users use 7.6 or older and they still have older `aeson` versions they can use to support their stale infrastructure and they are unlikely to avail themselves of newer `aeson` versions, it seems to me like the cost is minor to drop 7.6 support going forward. Also, as others have mentioned, the benefit of dropping 7.6 goes beyond just the `Ord` instance for `Value` because it would also help improve the maintainability of this project.

Indeed, the fact that `aeson` still doesn't have an `Ord` instance for `Value` is a indictment of the current maintainability of the `aeson` project.

**Comment by locallycompact** [comment] 2020-06-06 10:34
I ran into this today and wondering what the state of this is.

**Comment by phadej** [comment] 2020-06-06 11:34
Just forgotten. We indeed dropped support for pre-GHC-7.8. So let me see.

**Closed** 2020-06-08 23:01 UTC
