### ISSUE TITLE
Separate `Data.Aeson.Parser.Time` into separate package

### ISSUE THREAD

**Issue by phadej** [bos/aeson#507] opened 2017-02-01 05:55 UTC
There is my package `time-parsers`, but it's uses `parsers` abstraction. But e.g. in https://github.com/fizruk/http-api-data/issues/41 even the slight `parsec` + `parsers` overhead is non welcomed. Also using clearly the same package in `aeson` and `http-api-data` and others would be great. I propose `iso8601-attoparsec` name.

**Comment by bergmark** [comment] 2017-03-03 23:45
Sorry i missed this @phadej! I never mind a reminder by the way.

The pro is obvious, allowing others to re-use/collaborate on this.

Cons? This is just a mind dump:

1. Extra overhead when compiling (very slight...)
2. Extra overhead for maintaining a separate project
3. Might warrant sharing the test suite so aeson & others can use it as regression tests - this would need to be yet another package (or other form of distribution) - Might be a good idea regardless as it could also be used to guide other implementations
4. Everyone has to agree on changes to the format, otherwise we're back at square one - We recently made a breaking change to it
5. As mentioned everyone also has to agree on dependencies

An atypical solution would be to maintain this code as part of the aeson repo, using it as normal source files for aeson but also giving it its own .cabal file. That way point 1 and 3, and to some degree 2, would be moot.

**Comment by bergmark** [comment] 2017-03-19 00:36
@fizruk Would http-api-data use a time parsing package if it had minimal dependencies? Would you likely be ok with widening the format further if aeson chooses to do so in the future?

**Comment by fizruk** [comment] 2017-03-20 11:30
@bergmark I think `http-api-data` would be ok with any dependencies `aeson` would use, since `aeson` is a very common dependency for web projects. It just so happens that `parsec` isn't a transitive dependency for many web-based projects AFAICT, so dragging it solely for `http-api-data` would be very visible and would make `http-api-data` unnecessarily heavy. However, if `aeson` were to use `parsec`-based time parsing package, I would have no problems with using the same package.

I would very much like to have `http-api-data` time formats compatible with what `aeson` has, since it's often the case that same date/time parameters are passed both via query params and in JSON request/response bodies. It is unfortunate that currently those differ (although slightly, see https://github.com/fizruk/http-api-data/issues/41) in representation.

I would like to see this time parsing library in its own repo, but that's not a priority to me.

**Comment by fizruk** [comment] 2017-04-19 12:39
@bergmark I see #530 has been merged. Is there a plan to release the package sometime soon?

**Comment by bergmark** [comment] 2017-04-19 13:06
Yes! I'll try to do it tonight

**Comment by bergmark** [comment] 2017-04-20 08:05
@fizruk shipped!

**Comment by fizruk** [comment] 2017-04-20 12:31
Great! Thanks a lot!

@phadej I guess we can now close this issue?

**Closed** 2017-04-20 12:57 UTC
Labels: needs decision
