### ISSUE TITLE
deriveJSON generates invalid ToJSON toEncoding instance when omitNothingFields is True

### ISSUE THREAD

**Issue by Dridus** [bos/aeson#330] opened 2016-01-07 19:02 UTC
Using stackage LTS 4.0, including GHC 7.10.3 and Aeson 0.10.0.0. Pretty much as titled:

```haskell
{-# LANGUAGE TemplateHaskell #-}
module Main where

import Data.Aeson (encode)
import Data.Aeson.TH (defaultOptions, deriveJSON, omitNothingFields)

data Foo = Foo
  { first :: Maybe Int
  , second :: Int }

deriveJSON defaultOptions { omitNothingFields = True } ''Foo

main :: IO ()
main = putStrLn . show . encode $ Foo Nothing 123
```

```
ross@Endurance ~ > stack ghc foo.hs
Run from outside a project, using implicit global project config
Using resolver: lts-4.0 from implicit global project's config file: /Users/ross/.stack/global-project/stack.yaml
[1 of 1] Compiling Main             ( foo.hs, foo.o )

foo.hs:11:1:
    Couldn't match expected type ‘Data.Text.Internal.Text’
                with actual type ‘Data.ByteString.Builder.Internal.Builder’
    In the first argument of ‘(aeson-0.10.0.0:Data.Aeson.Types.Class..=)’, namely
      ‘aeson-0.10.0.0:Data.Aeson.Encode.Builder.text
         (Data.Text.pack "first")’
    In the first argument of ‘(<$>)’, namely
      ‘(aeson-0.10.0.0:Data.Aeson.Encode.Builder.text
          (Data.Text.pack "first")
        aeson-0.10.0.0:Data.Aeson.Types.Class..=)’
```

if I change `omitNothingFields` to `False`, it compiles fine.

Based on a previous issue where @bos disavowed any TH related issues, I'm mentioning @basvandijk. Hopefully that's not out of turn!

**Comment by wereHamster** [comment] 2016-01-08 05:43
Duplicate of #293.

**Closed** 2016-01-22 18:44 UTC
