### ISSUE TITLE
Decoding 'Maybe Whatever' with .: doesn't throw an error at compile time

### ISSUE THREAD

**Issue by donkeybonks** [bos/aeson#614] opened 2017-12-24 23:55 UTC
Decoding 'Maybe Whatever' with (.:) doesn't throw an error at compile time. It just lets you know that it fails at run time, throwing an error instead of returning Nothing when the key doesn't exist.

This really isn't ideal. Could the API be 'safe-by-default' and only allow you to decode Maybe Whatever with (.:?) and not (.:) ? In my use cases I've never wanted to fail at runtime if the key doesn't exist and I intended to decode 'Maybe Whatever' but forgot to update the FromJSON instance.

**Comment by phadej** [comment] 2017-12-25 01:10
there are *good* semantics for `FromJSON (Maybe a)`, `null` decodes to `Nothing`, and something else decodes to `a`. This measn that key&value should exist in the JSON object. `.:?` would also succeed with `Nothing` when key doesn't exist.

In fact we have [`.:!`](http://hackage.haskell.org/package/aeson-1.2.3.0/docs/Data-Aeson-Types.html#v:.:-33-) to return `Nothing` if  key&value doesn't exist, but otherwise parse as intended.
Therefore, one can parse to `Maybe (Maybe Whaverer) with `.:!`, distinguishing between successful, non-existing and null cases.

I'm afraid there is no simple way to change `aeson` so it would be "safe-by-default", somebody will be unhappy with a change! I recommend you to use generic/TH deriving, it's very capable. `Maybe` instance *is* useful, yet generics or TH can `omitNothingFields` and rename fields with `fieldLabelModifier`.

**Comment by phadej** [comment] 2017-12-25 01:14
*EDIT:* we could make the default better by reworking whole `aeson` API: we could have `FromJSONField` type class, then `FromJSONField (Maybe a)` *could* "succeed" with `Nothing` if key doesn't exist. That's however very major change. Something like that is in #564 e.g.

**Comment by bergmark** [comment] 2020-06-14 04:05
I think we can close this.

**Closed by bergmark** 2020-06-14 04:05 UTC
