### ISSUE TITLE
omitNothingFields is broken

### ISSUE THREAD

**Issue by tejon** [bos/aeson#306] opened 2015-10-18 08:03 UTC
data Foo = Foo { bar :: Maybe Int } deriving Show
    $(deriveJSON defaultOptions{omitNothingFields=True} ''Foo)

    Error: Couldn't match expected type `Text' with actual type `Builder'
    In the first argument of `(.=)', namely `text (pack "bar")'
    In the first argument of `(<$>)', namely `(text (pack "bar") .=)'

Maybe fallout related to #287? But here's the weird thing, I actually discovered this first:

    type Synonym = Maybe Int
    data Foo = Foo { bar :: Synonym } deriving Show
    $(deriveJSON defaultOptions{omitNothingFields=True} ''Foo)

    >>> decode "{}" :: Maybe Foo
    Just (Foo {bar = Nothing})
    >>> encode $ Foo Nothing
    "{\"bar\":null}"

`omitNothingFields` wasn't omitting them. I removed the `type` for sanity checking, and it exploded! (I was working with more complex types, but this simple example shows the same behavior.) So this might be two bugs; for some reason a synonym prevents the compile failure, but still has wrong behavior.

Everything works fine when `omitNothingFields=False`.

**Comment by basvandijk** [comment] 2015-10-18 18:28
The `Couldn't match expected type 'Text' with actual type 'Builder'` error is a duplicate of #293 which is fixed in HEAD.

I will look into why Nothing fields aren't omitted in:

```
encode $ Foo Nothing
"{\"bar\":null}"
```

**Comment by bergmark** [comment] 2016-01-23 15:33
Nothing fields are omitted on master so I'll close this.

```
λ> encode $ Foo Nothing
"{}"
```

**Closed by bergmark** 2016-01-23 15:33 UTC
