### ISSUE TITLE
`FromJSON`/`ToJSON` instance lists missing from haddocks

### ISSUE THREAD

**Issue by Gabriel439** [bos/aeson#438] opened 2016-07-02 16:05 UTC
For some reason the instance lists for `FromJSON`/`ToJSON` don't render at all for the more recent versions of `aeson`, which makes it a bit difficult to figure out what instances are available.  The workaround at the moment is to browse the instance lists for an older version of the library.

**Comment by phadej** [comment] 2016-07-02 18:10
This is duplicate of https://github.com/bos/aeson/issues/375. Will be fixed in the next release.

**Closed** 2016-07-03 13:25 UTC

**Comment by Gabriel439** [comment] 2016-07-03 17:16
Thanks! :)
